---
- name: Retrieve Cisco router configurations
  hosts: R1:R2:R3:R4
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Show running configuration
      ios_config:
        commands:
          - show running-config
      register: config_output

    - name: Display configuration output
      debug:
        var: config_output.stdout_lines
